---
http:
- port: 8081
  endpoints:
  - uri: "/get"
    status: 200
    body: "OK"
    latency:
      min: 10
      max: 50

  - uri: "/bad"
    status: 500
    body: "BAD"
    latency:
      min: 1
      max: 5

---
thrift:
- port: 8082
  endpoints:
    - function: "test"
      latency:
        min: 10
        max: 100
